export function createPlaylistsModule() {
  return {
    playlistList: [],
    playlistListQuery: "",
    selectedPlaylistId: null,
    modals: { addMedia: false, createPlaylist: false, mediaImport: false },
    createPlaylistName: "",
    createPlaylistDesc: "",
    createPlaylistMediaIds: [],
    createPlaylistMediaTagQuery: "",
    createPlaylistMediaTagOpen: false,
    createPlaylistAvatarFile: null,
    createPlaylistBackgroundFile: null,
    playlistPageId: null,
    playlistDetail: null,
    playlistSubview: "main",
    playlistSelectedDate: "",
    playlistDayVideos: [],
    playlistDayVideosLoading: false,
    playlistDayVideosError: "",
    playlistCurrentVideo: null,
    playlistAudioOnly: false,
    playlistPlayerVideoUrl: "",
    playlistPlayerAudioUrl: "",
    playlistPlayerError: "",
    playlistPlayerNeedsDownload: false,
    playlistTranscriptText: "",
    playlistTranscriptLoading: false,
    playlistTranscriptError: "",
    playlistTranscriptLanguage: "",
    playlistTranscriptSource: "",
    playlistTranscriptActiveSource: "",
    playlistTranscriptVariant: "",
    playlistTranscriptSelectedVariant: "",
    playlistTranscriptAvailableVariants: { plain: false, polished: false },
    playlistTranscriptUpdatedAt: "",
    playlistTranscriptSwitching: false,
    playlistBriefHtml: "",
    playlistBriefMarkdown: "",
    playlistBriefSpeechText: "",
    playlistBriefSpeechSupported:
      typeof window !== "undefined" &&
      typeof window.speechSynthesis !== "undefined" &&
      typeof window.SpeechSynthesisUtterance === "function",
    playlistBriefSpeaking: false,
    playlistBriefSpeechError: "",
    playlistBriefSpeakingKey: "",
    playlistBriefLoading: false,
    playlistBriefError: "",
    playlistBriefGeneratingKey: "",
    playlistBriefAutoRequests: new Set(),
    playlistBriefAutoPoll: new Map(),
    playlistBriefCopying: false,
    playlistBriefPromptCopying: false,
    playlistMediaDurationSec: 0,
    playlistMediaCurrentTimeSec: 0,
    playlistMediaPlaying: false,
    playlistMediaMuted: false,
    playlistMediaVolume: 1,
    playlistPendingAutoPlayId: "",
    playlistTimelineStart: "",
    playlistTimelineEnd: "",
    playlistTimelineMax: 0,
    playlistTimelineValue: 0,
    playlistCalendarCount: 14,
    playlistCalendarAnchor: "",
    playlistCalendarCompact: false,
    playlistCalendarDragging: false,
    playlistCalendarSettling: false,
    playlistCalendarSettleStep: 0,
    playlistCalendarSuppressTransition: false,
    playlistCalendarDragPointerId: null,
    playlistCalendarDragStartX: 0,
    playlistCalendarDragStartY: 0,
    playlistCalendarDragOffsetX: 0,
    playlistCalendarDragDidMove: false,
    playlistCalendarDragSuppressClickUntil: 0,
    playlistDayListDragPointerId: null,
    playlistDayListDragStartX: 0,
    playlistDayListDragStartY: 0,
    playlistDayListDragOffsetX: 0,
    playlistDayListDragDidMove: false,
    playlistDayListSettling: false,
    playlistDayListDragSuppressClickUntil: 0,
    playlistDownloadSubmitting: false,
    playlistPeriodCounts: new Map(),
    playlistPeriodCountsKey: "",
    playlistPeriodCountsLoading: false,
    playlistPeriodCountsError: "",
    playlistPeriodCountsToken: 0,
    playlistSettingsGranularityDraft: "day",
    playlistSettingsGranularitySaving: false,
    playlistSettingsGranularityError: "",
    playlistSettingsPromptDraft: "",
    playlistSettingsPromptSaving: false,
    playlistSettingsPromptError: "",
    playlistNameEditing: false,
    playlistNameDraft: "",
    playlistNameSaving: false,
    playlistDescEditing: false,
    playlistDescDraft: "",
    playlistDescSaving: false,
    playlistEditMediaOpen: false,
    playlistEditMediaIds: [],
    playlistEditMediaTagQuery: "",
    playlistEditMediaTagOpen: false,
    playlistLoadToken: 0,
    _playlistDayAbortCtrl: null,
    _playlistBriefAbortCtrl: null,
    _playlistBriefMdAbortCtrl: null,
    _playlistBriefSpeechUtterance: null,
    _playlistPlayableProbeAbortCtrl: null,
    _playlistSelectAbortCtrl: null,
    _playlistTranscriptVariantAbortCtrl: null,
    _playlistCalendarDragMove: null,
    _playlistCalendarDragEnd: null,
    _playlistDayListDragMove: null,
    _playlistDayListDragEnd: null,
    _playlistDayListSettleTimer: null,
    _playlistCalendarSettleTimer: null,
    _playlistCalendarTransitionRaf1: null,
    _playlistCalendarTransitionRaf2: null,
    playlistAudioThumbnailFailures: new Map(),
    playlistAudioThumbnailSources: new Map(),
    playlistVideoAssetsCache: new Map(),
    playlistVideoTranscriptCache: new Map(),
    playlistBriefHtmlCache: new Map(),
    playlistBriefMarkdownCache: new Map(),
  };
}
