export function createSettingsModule() {
  return {
    settingsTab: "cookies",
    ytdlpCookiesText: "",
    ytdlpCookiesLoaded: false,
    ytdlpCookiesSaving: false,
    ytdlpCookiesError: "",
    ytdlpSubtitlesEnabled: false,
    ytdlpSubtitlesLoaded: false,
    ytdlpSubtitlesSaving: false,
    ytdlpSubtitlesError: "",
    ytdlpMembersOnlyEnabled: false,
    ytdlpMembersOnlyLoaded: false,
    ytdlpMembersOnlySaving: false,
    ytdlpMembersOnlyError: "",
    ytdlpFormatPreset: "1080",
    ytdlpFormatCustomText: "",
    ytdlpFormatLoaded: false,
    ytdlpFormatSaving: false,
    ytdlpFormatError: "",
    llmPolishPromptText: "",
    llmPolishPromptDefaultText: "",
    llmPolishPromptLoaded: false,
    llmPolishPromptSaving: false,
    llmPolishPromptLoadingDefault: false,
    llmPolishPromptError: "",
    staleVideosCleanupCount: 0,
    staleVideosCleanupItems: [],
    staleVideosCleanupHasMore: false,
    staleVideosCleanupLoaded: false,
    staleVideosCleanupLoading: false,
    staleVideosCleanupDeleting: false,
    staleVideosCleanupError: "",
  };
}
