export function createUsageModule() {
  return {
    usageDays: 90,
    usagePayload: null,
    usageGeneratedAt: "",
    usageTimezone: "",
    usageWindow: null,
    usageSummary: {
      downloadedVideoCount: null,
      videoDownloaded: null,
      externalCalls: null,
      llmCalls: null,
      asrCalls: null,
      embeddingCalls: null,
      llmInputTokens: null,
      llmOutputTokens: null,
      llmTotalTokens: null,
      assetCount: null,
      assetSizeBytes: null,
      assetMissingSizeCount: null,
      databaseSizeBytes: null,
    },
    usageSeries: [],
    usageServiceBreakdown: [],
    usageAssetBreakdown: [],
    usageCollection: {
      usageStartedAt: null,
      lastUsageAt: null,
      resourceStartedAt: null,
      lastResourceSnapshotAt: null,
      physicalStorageAvailable: false,
      physicalStorageReason: "",
    },
    usageLoading: false,
    usageError: "",
    usageChartError: "",
    usageCharts: {},
    _usageRequestToken: 0,
    _usageChartRetryTimer: null,
  };
}
